# Generated by Django 5.1.8 on 2025-05-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Taco', 'Taco'), ('Supreme Taco', 'Supreme Taco'), ('Quesadilla', 'Quesadilla'), ('Burrito', 'Burrito'), ('Nachos', 'Nachos'), ('Arroz con Pollo', 'Arroz con Pollo')], max_length=100)),
                ('meat', models.CharField(choices=[('Steak', 'Steak'), ('Chicken', 'Chicken'), ('Pastor', 'Pastor'), ('Chorizo', 'Chorizo'), ('Ground Beef', 'Ground Beef')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
