# Generated by Django 5.1.8 on 2025-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTruck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='meat',
            field=models.CharField(choices=[('Ground Beef', 'Ground Beef'), ('Steak', 'Steak'), ('Chicken', 'Chicken')], max_length=50),
        ),
    ]
