# Generated by Django 5.1.8 on 2025-05-07 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodTruck', '0002_customer_alter_fooditem_meat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodTruck.customer')),
                ('item', models.ManyToManyField(to='FoodTruck.fooditem')),
            ],
        ),
    ]
